// <auto-generated />
using Catalog.Presitence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Presitence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220412025119_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ice")
                        .HasColumnType("bit");

                    b.Property<bool>("Iva")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceOne")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceThree")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceTwo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Code = "P001",
                            Description = "Description for product 1",
                            Ice = false,
                            Iva = true,
                            Name = "Product 1",
                            PriceOne = 455m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 2,
                            Code = "P002",
                            Description = "Description for product 2",
                            Ice = false,
                            Iva = true,
                            Name = "Product 2",
                            PriceOne = 941m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 3,
                            Code = "P003",
                            Description = "Description for product 3",
                            Ice = false,
                            Iva = true,
                            Name = "Product 3",
                            PriceOne = 493m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 4,
                            Code = "P004",
                            Description = "Description for product 4",
                            Ice = false,
                            Iva = true,
                            Name = "Product 4",
                            PriceOne = 415m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 5,
                            Code = "P005",
                            Description = "Description for product 5",
                            Ice = false,
                            Iva = true,
                            Name = "Product 5",
                            PriceOne = 356m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 6,
                            Code = "P006",
                            Description = "Description for product 6",
                            Ice = false,
                            Iva = true,
                            Name = "Product 6",
                            PriceOne = 521m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 7,
                            Code = "P007",
                            Description = "Description for product 7",
                            Ice = false,
                            Iva = true,
                            Name = "Product 7",
                            PriceOne = 853m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 8,
                            Code = "P008",
                            Description = "Description for product 8",
                            Ice = false,
                            Iva = true,
                            Name = "Product 8",
                            PriceOne = 990m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 9,
                            Code = "P009",
                            Description = "Description for product 9",
                            Ice = false,
                            Iva = true,
                            Name = "Product 9",
                            PriceOne = 340m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 10,
                            Code = "P0010",
                            Description = "Description for product 10",
                            Ice = false,
                            Iva = true,
                            Name = "Product 10",
                            PriceOne = 510m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 11,
                            Code = "P0011",
                            Description = "Description for product 11",
                            Ice = false,
                            Iva = true,
                            Name = "Product 11",
                            PriceOne = 201m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 12,
                            Code = "P0012",
                            Description = "Description for product 12",
                            Ice = false,
                            Iva = true,
                            Name = "Product 12",
                            PriceOne = 405m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 13,
                            Code = "P0013",
                            Description = "Description for product 13",
                            Ice = false,
                            Iva = true,
                            Name = "Product 13",
                            PriceOne = 501m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 14,
                            Code = "P0014",
                            Description = "Description for product 14",
                            Ice = false,
                            Iva = true,
                            Name = "Product 14",
                            PriceOne = 524m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 15,
                            Code = "P0015",
                            Description = "Description for product 15",
                            Ice = false,
                            Iva = true,
                            Name = "Product 15",
                            PriceOne = 825m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 16,
                            Code = "P0016",
                            Description = "Description for product 16",
                            Ice = false,
                            Iva = true,
                            Name = "Product 16",
                            PriceOne = 597m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 17,
                            Code = "P0017",
                            Description = "Description for product 17",
                            Ice = false,
                            Iva = true,
                            Name = "Product 17",
                            PriceOne = 358m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 18,
                            Code = "P0018",
                            Description = "Description for product 18",
                            Ice = false,
                            Iva = true,
                            Name = "Product 18",
                            PriceOne = 597m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 19,
                            Code = "P0019",
                            Description = "Description for product 19",
                            Ice = false,
                            Iva = true,
                            Name = "Product 19",
                            PriceOne = 384m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 20,
                            Code = "P0020",
                            Description = "Description for product 20",
                            Ice = false,
                            Iva = true,
                            Name = "Product 20",
                            PriceOne = 336m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 21,
                            Code = "P0021",
                            Description = "Description for product 21",
                            Ice = false,
                            Iva = true,
                            Name = "Product 21",
                            PriceOne = 261m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 22,
                            Code = "P0022",
                            Description = "Description for product 22",
                            Ice = false,
                            Iva = true,
                            Name = "Product 22",
                            PriceOne = 374m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 23,
                            Code = "P0023",
                            Description = "Description for product 23",
                            Ice = false,
                            Iva = true,
                            Name = "Product 23",
                            PriceOne = 557m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 24,
                            Code = "P0024",
                            Description = "Description for product 24",
                            Ice = false,
                            Iva = true,
                            Name = "Product 24",
                            PriceOne = 454m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 25,
                            Code = "P0025",
                            Description = "Description for product 25",
                            Ice = false,
                            Iva = true,
                            Name = "Product 25",
                            PriceOne = 232m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 26,
                            Code = "P0026",
                            Description = "Description for product 26",
                            Ice = false,
                            Iva = true,
                            Name = "Product 26",
                            PriceOne = 423m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 27,
                            Code = "P0027",
                            Description = "Description for product 27",
                            Ice = false,
                            Iva = true,
                            Name = "Product 27",
                            PriceOne = 857m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 28,
                            Code = "P0028",
                            Description = "Description for product 28",
                            Ice = false,
                            Iva = true,
                            Name = "Product 28",
                            PriceOne = 182m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 29,
                            Code = "P0029",
                            Description = "Description for product 29",
                            Ice = false,
                            Iva = true,
                            Name = "Product 29",
                            PriceOne = 305m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 30,
                            Code = "P0030",
                            Description = "Description for product 30",
                            Ice = false,
                            Iva = true,
                            Name = "Product 30",
                            PriceOne = 997m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 31,
                            Code = "P0031",
                            Description = "Description for product 31",
                            Ice = false,
                            Iva = true,
                            Name = "Product 31",
                            PriceOne = 291m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 32,
                            Code = "P0032",
                            Description = "Description for product 32",
                            Ice = false,
                            Iva = true,
                            Name = "Product 32",
                            PriceOne = 975m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 33,
                            Code = "P0033",
                            Description = "Description for product 33",
                            Ice = false,
                            Iva = true,
                            Name = "Product 33",
                            PriceOne = 685m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 34,
                            Code = "P0034",
                            Description = "Description for product 34",
                            Ice = false,
                            Iva = true,
                            Name = "Product 34",
                            PriceOne = 365m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 35,
                            Code = "P0035",
                            Description = "Description for product 35",
                            Ice = false,
                            Iva = true,
                            Name = "Product 35",
                            PriceOne = 176m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 36,
                            Code = "P0036",
                            Description = "Description for product 36",
                            Ice = false,
                            Iva = true,
                            Name = "Product 36",
                            PriceOne = 475m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 37,
                            Code = "P0037",
                            Description = "Description for product 37",
                            Ice = false,
                            Iva = true,
                            Name = "Product 37",
                            PriceOne = 837m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 38,
                            Code = "P0038",
                            Description = "Description for product 38",
                            Ice = false,
                            Iva = true,
                            Name = "Product 38",
                            PriceOne = 270m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 39,
                            Code = "P0039",
                            Description = "Description for product 39",
                            Ice = false,
                            Iva = true,
                            Name = "Product 39",
                            PriceOne = 765m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 40,
                            Code = "P0040",
                            Description = "Description for product 40",
                            Ice = false,
                            Iva = true,
                            Name = "Product 40",
                            PriceOne = 757m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 41,
                            Code = "P0041",
                            Description = "Description for product 41",
                            Ice = false,
                            Iva = true,
                            Name = "Product 41",
                            PriceOne = 226m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 42,
                            Code = "P0042",
                            Description = "Description for product 42",
                            Ice = false,
                            Iva = true,
                            Name = "Product 42",
                            PriceOne = 539m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 43,
                            Code = "P0043",
                            Description = "Description for product 43",
                            Ice = false,
                            Iva = true,
                            Name = "Product 43",
                            PriceOne = 101m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 44,
                            Code = "P0044",
                            Description = "Description for product 44",
                            Ice = false,
                            Iva = true,
                            Name = "Product 44",
                            PriceOne = 556m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 45,
                            Code = "P0045",
                            Description = "Description for product 45",
                            Ice = false,
                            Iva = true,
                            Name = "Product 45",
                            PriceOne = 877m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 46,
                            Code = "P0046",
                            Description = "Description for product 46",
                            Ice = false,
                            Iva = true,
                            Name = "Product 46",
                            PriceOne = 900m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 47,
                            Code = "P0047",
                            Description = "Description for product 47",
                            Ice = false,
                            Iva = true,
                            Name = "Product 47",
                            PriceOne = 279m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 48,
                            Code = "P0048",
                            Description = "Description for product 48",
                            Ice = false,
                            Iva = true,
                            Name = "Product 48",
                            PriceOne = 204m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 49,
                            Code = "P0049",
                            Description = "Description for product 49",
                            Ice = false,
                            Iva = true,
                            Name = "Product 49",
                            PriceOne = 737m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 50,
                            Code = "P0050",
                            Description = "Description for product 50",
                            Ice = false,
                            Iva = true,
                            Name = "Product 50",
                            PriceOne = 541m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 51,
                            Code = "P0051",
                            Description = "Description for product 51",
                            Ice = false,
                            Iva = true,
                            Name = "Product 51",
                            PriceOne = 526m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 52,
                            Code = "P0052",
                            Description = "Description for product 52",
                            Ice = false,
                            Iva = true,
                            Name = "Product 52",
                            PriceOne = 204m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 53,
                            Code = "P0053",
                            Description = "Description for product 53",
                            Ice = false,
                            Iva = true,
                            Name = "Product 53",
                            PriceOne = 620m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 54,
                            Code = "P0054",
                            Description = "Description for product 54",
                            Ice = false,
                            Iva = true,
                            Name = "Product 54",
                            PriceOne = 969m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 55,
                            Code = "P0055",
                            Description = "Description for product 55",
                            Ice = false,
                            Iva = true,
                            Name = "Product 55",
                            PriceOne = 728m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 56,
                            Code = "P0056",
                            Description = "Description for product 56",
                            Ice = false,
                            Iva = true,
                            Name = "Product 56",
                            PriceOne = 181m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 57,
                            Code = "P0057",
                            Description = "Description for product 57",
                            Ice = false,
                            Iva = true,
                            Name = "Product 57",
                            PriceOne = 484m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 58,
                            Code = "P0058",
                            Description = "Description for product 58",
                            Ice = false,
                            Iva = true,
                            Name = "Product 58",
                            PriceOne = 139m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 59,
                            Code = "P0059",
                            Description = "Description for product 59",
                            Ice = false,
                            Iva = true,
                            Name = "Product 59",
                            PriceOne = 282m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 60,
                            Code = "P0060",
                            Description = "Description for product 60",
                            Ice = false,
                            Iva = true,
                            Name = "Product 60",
                            PriceOne = 933m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 61,
                            Code = "P0061",
                            Description = "Description for product 61",
                            Ice = false,
                            Iva = true,
                            Name = "Product 61",
                            PriceOne = 664m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 62,
                            Code = "P0062",
                            Description = "Description for product 62",
                            Ice = false,
                            Iva = true,
                            Name = "Product 62",
                            PriceOne = 770m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 63,
                            Code = "P0063",
                            Description = "Description for product 63",
                            Ice = false,
                            Iva = true,
                            Name = "Product 63",
                            PriceOne = 784m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 64,
                            Code = "P0064",
                            Description = "Description for product 64",
                            Ice = false,
                            Iva = true,
                            Name = "Product 64",
                            PriceOne = 342m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 65,
                            Code = "P0065",
                            Description = "Description for product 65",
                            Ice = false,
                            Iva = true,
                            Name = "Product 65",
                            PriceOne = 319m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 66,
                            Code = "P0066",
                            Description = "Description for product 66",
                            Ice = false,
                            Iva = true,
                            Name = "Product 66",
                            PriceOne = 226m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 67,
                            Code = "P0067",
                            Description = "Description for product 67",
                            Ice = false,
                            Iva = true,
                            Name = "Product 67",
                            PriceOne = 720m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 68,
                            Code = "P0068",
                            Description = "Description for product 68",
                            Ice = false,
                            Iva = true,
                            Name = "Product 68",
                            PriceOne = 235m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 69,
                            Code = "P0069",
                            Description = "Description for product 69",
                            Ice = false,
                            Iva = true,
                            Name = "Product 69",
                            PriceOne = 448m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 70,
                            Code = "P0070",
                            Description = "Description for product 70",
                            Ice = false,
                            Iva = true,
                            Name = "Product 70",
                            PriceOne = 449m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 71,
                            Code = "P0071",
                            Description = "Description for product 71",
                            Ice = false,
                            Iva = true,
                            Name = "Product 71",
                            PriceOne = 759m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 72,
                            Code = "P0072",
                            Description = "Description for product 72",
                            Ice = false,
                            Iva = true,
                            Name = "Product 72",
                            PriceOne = 188m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 73,
                            Code = "P0073",
                            Description = "Description for product 73",
                            Ice = false,
                            Iva = true,
                            Name = "Product 73",
                            PriceOne = 832m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 74,
                            Code = "P0074",
                            Description = "Description for product 74",
                            Ice = false,
                            Iva = true,
                            Name = "Product 74",
                            PriceOne = 627m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 75,
                            Code = "P0075",
                            Description = "Description for product 75",
                            Ice = false,
                            Iva = true,
                            Name = "Product 75",
                            PriceOne = 210m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 76,
                            Code = "P0076",
                            Description = "Description for product 76",
                            Ice = false,
                            Iva = true,
                            Name = "Product 76",
                            PriceOne = 722m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 77,
                            Code = "P0077",
                            Description = "Description for product 77",
                            Ice = false,
                            Iva = true,
                            Name = "Product 77",
                            PriceOne = 373m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 78,
                            Code = "P0078",
                            Description = "Description for product 78",
                            Ice = false,
                            Iva = true,
                            Name = "Product 78",
                            PriceOne = 100m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 79,
                            Code = "P0079",
                            Description = "Description for product 79",
                            Ice = false,
                            Iva = true,
                            Name = "Product 79",
                            PriceOne = 576m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 80,
                            Code = "P0080",
                            Description = "Description for product 80",
                            Ice = false,
                            Iva = true,
                            Name = "Product 80",
                            PriceOne = 331m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 81,
                            Code = "P0081",
                            Description = "Description for product 81",
                            Ice = false,
                            Iva = true,
                            Name = "Product 81",
                            PriceOne = 243m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 82,
                            Code = "P0082",
                            Description = "Description for product 82",
                            Ice = false,
                            Iva = true,
                            Name = "Product 82",
                            PriceOne = 752m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 83,
                            Code = "P0083",
                            Description = "Description for product 83",
                            Ice = false,
                            Iva = true,
                            Name = "Product 83",
                            PriceOne = 444m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 84,
                            Code = "P0084",
                            Description = "Description for product 84",
                            Ice = false,
                            Iva = true,
                            Name = "Product 84",
                            PriceOne = 764m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 85,
                            Code = "P0085",
                            Description = "Description for product 85",
                            Ice = false,
                            Iva = true,
                            Name = "Product 85",
                            PriceOne = 571m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 86,
                            Code = "P0086",
                            Description = "Description for product 86",
                            Ice = false,
                            Iva = true,
                            Name = "Product 86",
                            PriceOne = 187m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 87,
                            Code = "P0087",
                            Description = "Description for product 87",
                            Ice = false,
                            Iva = true,
                            Name = "Product 87",
                            PriceOne = 455m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 88,
                            Code = "P0088",
                            Description = "Description for product 88",
                            Ice = false,
                            Iva = true,
                            Name = "Product 88",
                            PriceOne = 715m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 89,
                            Code = "P0089",
                            Description = "Description for product 89",
                            Ice = false,
                            Iva = true,
                            Name = "Product 89",
                            PriceOne = 637m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 90,
                            Code = "P0090",
                            Description = "Description for product 90",
                            Ice = false,
                            Iva = true,
                            Name = "Product 90",
                            PriceOne = 994m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 91,
                            Code = "P0091",
                            Description = "Description for product 91",
                            Ice = false,
                            Iva = true,
                            Name = "Product 91",
                            PriceOne = 990m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 92,
                            Code = "P0092",
                            Description = "Description for product 92",
                            Ice = false,
                            Iva = true,
                            Name = "Product 92",
                            PriceOne = 798m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 93,
                            Code = "P0093",
                            Description = "Description for product 93",
                            Ice = false,
                            Iva = true,
                            Name = "Product 93",
                            PriceOne = 987m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 94,
                            Code = "P0094",
                            Description = "Description for product 94",
                            Ice = false,
                            Iva = true,
                            Name = "Product 94",
                            PriceOne = 831m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 95,
                            Code = "P0095",
                            Description = "Description for product 95",
                            Ice = false,
                            Iva = true,
                            Name = "Product 95",
                            PriceOne = 192m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 96,
                            Code = "P0096",
                            Description = "Description for product 96",
                            Ice = false,
                            Iva = true,
                            Name = "Product 96",
                            PriceOne = 455m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 97,
                            Code = "P0097",
                            Description = "Description for product 97",
                            Ice = false,
                            Iva = true,
                            Name = "Product 97",
                            PriceOne = 754m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 98,
                            Code = "P0098",
                            Description = "Description for product 98",
                            Ice = false,
                            Iva = true,
                            Name = "Product 98",
                            PriceOne = 758m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        },
                        new
                        {
                            ProductId = 99,
                            Code = "P0099",
                            Description = "Description for product 99",
                            Ice = false,
                            Iva = true,
                            Name = "Product 99",
                            PriceOne = 337m,
                            PriceThree = 0m,
                            PriceTwo = 0m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductInStockId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 3
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
